# Generated by Django 6.0.1 on 2026-02-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_pedania_anuncio_comentario_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='organizador',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='cupo_maximo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='otros', max_length=20),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='asistido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_entidad',
            field=models.CharField(blank=True, help_text='Rellenar solo si es organización (ej: Cruz Roja)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_evento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('voluntario', 'Voluntario'), ('organizacion', 'Organizacion / Entidad'), ('Administrador', 'Administrador de la plataforma')], default='voluntario', max_length=20),
        ),
    ]
