# Generated by Django 6.0.1 on 2026-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0003_remove_anuncio_organizador_anuncio_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='pedania',
            options={'verbose_name': 'Pedanía', 'verbose_name_plural': 'Pedanías'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='patrocinadores/')),
                ('sitio_web', models.URLField(blank=True, help_text='Link a la web del patrocinador', null=True)),
                ('anuncios', models.ManyToManyField(blank=True, related_name='patrocinadores', to='voluntariado.anuncio')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
    ]
