# Generated by Django 6.0.1 on 2026-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0004_alter_anuncio_options_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='noticia_imagen',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la noticia', null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='noticia_resumen',
            field=models.TextField(blank=True, help_text='Resumen de lo logrado en la actividad', null=True),
        ),
    ]
