# Generated by Django 6.0.1 on 2026-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0005_anuncio_noticia_imagen_anuncio_noticia_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='requerimientos',
            field=models.TextField(blank=True, help_text='Requisitos para participar (ej: traer agua, guantes, mayor de edad...)', null=True),
        ),
    ]
